apiVersion: v1
kind: Service
metadata:
  annotations:
    cloud.google.com/neg: '{"ingress":true}'
  creationTimestamp: "2022-01-03T21:09:35Z"
  finalizers:
  - service.kubernetes.io/load-balancer-cleanup
  labels:
    app: kamere
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:labels:
          .: {}
          f:app: {}
      f:spec:
        f:externalTrafficPolicy: {}
        f:ports:
          .: {}
          k:{"port":80,"protocol":"TCP"}:
            .: {}
            f:port: {}
            f:protocol: {}
            f:targetPort: {}
        f:selector:
          .: {}
          f:app: {}
        f:sessionAffinity: {}
        f:type: {}
    manager: GoogleCloudConsole
    operation: Update
    time: "2022-01-03T21:09:35Z"
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:finalizers:
          .: {}
          v:"service.kubernetes.io/load-balancer-cleanup": {}
    manager: kube-controller-manager
    operation: Update
    time: "2022-01-03T21:09:35Z"
  name: kamere-service
  namespace: default
  resourceVersion: "2372560"
  uid: 684d7f85-5b90-4219-9271-f1553a724872
spec:
  clusterIP: 10.8.11.163
  clusterIPs:
  - 10.8.11.163
  externalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 32060
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: kamere
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer: {}
